### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by jtpio** [mamba-org/setup-mamba#4]
First tests on running the action with `windows-latest` were done in https://github.com/TheSnakePit/setup-mamba/pull/3.

Here is an example of a failed run: https://github.com/TheSnakePit/setup-mamba/runs/741565038

With the following output:

```
Run mamba install -y -c conda-forge python
  mamba install -y -c conda-forge python
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: DLL load failed: The specified module could not be found.
##[error]Process completed with exit code 1.
```

**Comment by dhirschfeld** [comment]
Something is pretty badly broken if you're getting DLL errors! 😬

**Comment by dhirschfeld** [comment]
I don't know much about the GitHub Actions runners. Have the shells been initialised for `conda`? Are you running the commands from the activated environment where `mamba` is installed.

I see it's running the latest and greatest `pwsh` 7. I haven't used that yet so I don't even know if `conda` works with that shell.

**Comment by dhirschfeld** [comment]
* https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/
* https://github.community/t/windows-is-using-powershell-core-instead-of-powershell-as-documented/16741

If you're not using any powershell features I'd try using `shell: cmd`, otherwise `shell: powershell` will get you the old-fangled powershell which might work better with `conda`

**Comment by jtpio** [comment]
Closing in favor of https://github.com/mamba-org/setup-micromamba
